"""
Section 29 — GraphRAG / Lab 02 — Community Detection & Hierarchical GraphRAG

Microsoft GraphRAG Architecture (Edge et al., 2024):
  - Solves the critical limitation of Vector RAG: failure on dataset-wide global aggregation queries.
  - Divides the extracted knowledge graph into modular communities using Leiden/Louvain graph clustering.
  - Generates hierarchical community reports at multiple abstraction levels (Level 0: Micro, Level 1: Macro).

Dual-Mode GraphRAG Retrieval:
  1. Local Search:
     - Entity-centric: traverses direct 1-hop and 2-hop graph neighbors of entities extracted from the query.
     - Best for: "How does the RateLimiter authenticate with Redis?"
  2. Global Search:
     - Map-Reduce over Community Summaries: Evaluates high-level community reports in parallel.
     - Best for: "What are the overarching architectural bottlenecks across all subsystems?"

Run:
  python graph_rag.py
"""

from typing import List, Dict, Set, Tuple, Any
from dataclasses import dataclass, field


@dataclass
class CommunityReport:
    community_id: int
    title: str
    summary: str
    entities: List[str]
    level: int  # 0 = granular cluster, 1 = macro domain


@dataclass
class GraphRAGResponse:
    query: str
    mode: str  # "GLOBAL_SEARCH" or "LOCAL_SEARCH"
    answer: str
    context_sources: List[str]


class HierarchicalGraphRAGEngine:
    """GraphRAG engine supporting Community Detection, Local Entity Search, and Global Map-Reduce."""

    def __init__(self):
        # Simulated Graph with 2 distinct communities
        self.entities = {
            "RateLimiter": {"type": "SERVICE", "community": 1, "desc": "Sliding window token bucket rate limiter"},
            "Redis": {"type": "CACHE", "community": 1, "desc": "In-memory cache for atomic counter increments"},
            "Envoy": {"type": "GATEWAY", "community": 1, "desc": "Edge API proxy routing requests and enforcing rate limits"},
            "OrderDB": {"type": "DATABASE", "community": 2, "desc": "PostgreSQL relational store for financial orders"},
            "PaymentGateway": {"type": "SERVICE", "community": 2, "desc": "Stripe/UPI 2-phase commit payment processor"},
            "Ledger": {"type": "LEDGER", "community": 2, "desc": "TigerBeetle immutable double-entry ledger"}
        }

        self.edges = [
            ("Envoy", "RateLimiter", "INVOKES_CHECK"),
            ("RateLimiter", "Redis", "GETS_BUCKET_STATE"),
            ("PaymentGateway", "OrderDB", "CREATES_ORDER"),
            ("PaymentGateway", "Ledger", "RECORDS_JOURNAL_ENTRY"),
            ("OrderDB", "Ledger", "RECONCILES_BALANCES")
        ]

        # Hierarchical Community Reports (Generated by LLM during indexing)
        self.community_reports = [
            CommunityReport(
                community_id=1,
                title="Traffic Ingress & Edge Protection Cluster",
                summary="Enforces traffic management, DDoS mitigation, and distributed rate limiting using Envoy and Redis.",
                entities=["Envoy", "RateLimiter", "Redis"],
                level=0
            ),
            CommunityReport(
                community_id=2,
                title="Transactional Order & Financial Settlement Cluster",
                summary="Processes e-commerce checkout transactions with double-entry ledger settlement and database persistence.",
                entities=["PaymentGateway", "OrderDB", "Ledger"],
                level=0
            )
        ]

    def local_search(self, entity_name: str) -> GraphRAGResponse:
        """Entity-focused local graph traversal."""
        key = entity_name.strip()
        matched = [e for e in self.entities if e.lower() == key.lower()]
        if not matched:
            return GraphRAGResponse(
                query=f"Details for {entity_name}",
                mode="LOCAL_SEARCH",
                answer=f"Entity '{entity_name}' not found in Knowledge Graph.",
                context_sources=[]
            )

        e_id = matched[0]
        e_info = self.entities[e_id]
        incident_edges = [f"({u} --[{r}]--> {v})" for u, v, r in self.edges if u == e_id or v == e_id]

        answer = f"Local Entity Profile: {e_id} ({e_info['type']}) - {e_info['desc']}. Direct connections: {', '.join(incident_edges)}"
        return GraphRAGResponse(
            query=f"Local search for {entity_name}",
            mode="LOCAL_SEARCH",
            answer=answer,
            context_sources=incident_edges
        )

    def global_search(self, global_query: str) -> GraphRAGResponse:
        """Global map-reduce search across all community reports."""
        # 1. Map phase: summarize insights from each community report
        community_insights = []
        for report in self.community_reports:
            community_insights.append(f"[{report.title} (Entities: {', '.join(report.entities)})]: {report.summary}")

        # 2. Reduce phase: synthesize global answer
        combined_synthesis = " | ".join(community_insights)
        answer = f"Global Architecture Synthesis for query '{global_query}': {combined_synthesis}"

        return GraphRAGResponse(
            query=global_query,
            mode="GLOBAL_SEARCH",
            answer=answer,
            context_sources=[f"Community_{r.community_id}" for r in self.community_reports]
        )


def main():
    print("=" * 75)
    print("Lab 02: GraphRAG Community Detection & Global vs Local Search")
    print("=" * 75)

    engine = HierarchicalGraphRAGEngine()

    # 1. Local Search Test (Entity query)
    print("\n--- 1. Local Search (Entity Traversal) ---")
    local_res = engine.local_search("RateLimiter")
    print(f"Query: {local_res.query}")
    print(f"Mode : {local_res.mode}")
    print(f"Answer: {local_res.answer}\n")

    # 2. Global Search Test (Broad thematic query)
    print("--- 2. Global Search (Map-Reduce over Community Summaries) ---")
    global_query = "What are the primary operational domains across the infrastructure?"
    global_res = engine.global_search(global_query)
    print(f"Query : {global_res.query}")
    print(f"Mode  : {global_res.mode}")
    print(f"Answer: {global_res.answer}")
    print(f"Sources: {global_res.context_sources}")


if __name__ == "__main__":
    main()
